- name: Install Wireguard
  apt:
      state: present
      update_cache: yes
      name:
          - wireguard
          - wireguard-tools

- name: Load Wireguard module
  command: modprobe wireguard
